env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'jest'
rules:
  {
    'import/extensions':
      ['error', 'ignorePackages', { 'js': 'never', 'jsx': 'never', 'ts': 'never', 'tsx': 'never' }],
  }
settings: { 'import/resolver': { typescript: {} } }
