language: node_js
node_js:
  - 14
jobs:
  include:
    - stage: release
      script:
        - npm run build
        - npm run lint
        - npm run test
        - npm run test:coverage
        - npm install codecov -g
cache:
  directories:
    - node_modules
after_success:
  - codecov
