# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install
              run: npm ci

            - name: Test
              run: npm run test
